#!/bin/bash

# @Author yasuhiro.yamada
# @Filename xpanes
readonly VERSION="1.3.0"

set -e

# THIS_FILE_NAME is supposed to be "xpanes".
readonly THIS_FILE_NAME="${0##*/}"
readonly THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-${(%):-%N}}")"; pwd)"
readonly ABS_THIS_FILE_NAME="$THIS_DIR/$THIS_FILE_NAME"

# This is supposed to be xpanes-12345(PID)
readonly SESSION_NAME="$THIS_FILE_NAME-$$"

# Temporary window name is tmp-12345(PID)
readonly TMP_WIN_NAME="tmp-$$"

XPANES_DEPENDENCIES="${XPANES_DEPENDENCIES:-tmux perl}"

__xpanes::usage() {
    echo "Usage:"
    echo "  $THIS_FILE_NAME [OPTIONS] [<USER NAME>@]<HOST NAME> [<USER NAME>@<HOST NAME> ...]"
    echo
    echo "OPTIONS:"
    echo "  -h --help                    Show this screen."
    echo "  -v --version                 Show version."
    echo "  -c utility                   Specify utility which is executed as a command in each panes. If utility is omitted, echo(1) is used."
    echo "  -I replstr                   Replacing one or more occurrences of replstr in utility given by -c option."
    echo "  -S socket-path               Specify a full alternative path to the server socket."
    echo "  -l --log[=<directory>]       Enable logging and store log files to $LOG_DIR or given <directory>."
    echo "     --log-format=<FORMAT>     File name of log files follows given <FORMAT>."
    echo
    echo " FORMAT:"
    echo "     Default value is \"$LOG_FORMAT\""
    echo "     Interpreted sequences are:"
    echo "     [:PID:]   Process id of the tmux session. (e.g, 41531)"
    echo "     [:ARG:]   Host name to which the pane is logging in. (e.g, userA@serverA)"
    echo
    echo '     In addition, sequences same as `date` command are available.'
    echo
    echo "     For example:"
    echo "     %Y   year  (e.g, 1960)"
    echo "     %m   month (e.g, 01)"
    echo "     %d   date  (e.g, 31)"
    echo "     And etc."
    echo "     Other sequences are available. Please refer to date(1) manual."
    echo
    echo " Examples:"
    echo "     $ $THIS_FILE_NAME host1 host2 host3 host4"
    echo "     New window is created and then, it will be separated into four panes."
    echo
    echo "     $ $THIS_FILE_NAME host{1..4}"
    echo "     Four panes will be created."
    echo "     Brace expansion is useful."
    echo
    echo "     $ $THIS_FILE_NAME -l user1@host1 user1@host1"
    echo "     New window is created and it will be separated into two panes."
    echo "     And also $LOG_DIR/user1@host1-1.log.2016-01-31_23-59-59.log"
    echo "     and      $LOG_DIR/user1@host1-2.log.2016-01-31_23-59-59.log"
    echo "     will be created as their log files."
    echo
    echo "     $ $THIS_FILE_NAME -l --log=/tmp/logs user1@host1 user2@host2"
    echo "     Following files will be created."
    echo "     /tmp/logs/user1@host1-1.log.2016-01-31_23-59-59.log"
    echo "     /tmp/logs/user2@host2-1.log.2016-01-31_23-59-59.log"
    echo "     will be created as their log files."
    echo
}

# Show version number
__xpanes::version() {
    echo "$THIS_FILE_NAME $VERSION"
}

__xpanes::get_tmux_conf() {
    local _conf_name="$1"
    tmux show-window-options -g | grep "^${1}" | head -n 1 | perl -anle 'print $F[1]'
}

#
# Generate log file names from given arguments.
# Usage:
#        echo <host1> <host2> ... | __xpanes::log_filenames <FORMAT>
# Return:
#        File names.
# Example:
#        $ echo aaa bbb ccc aaa ccc ccc | xargs -n 1 | log_filenames '[:ARG:]_[:PID:]_%Y%m%d.log'
#        aaa-1_1234_20160101.log
#        bbb-1_1234_20160101.log
#        ccc-1_1234_20160101.log
#        aaa-2_1234_20160101.log
#        ccc-2_1234_20160101.log
#        ccc-3_1234_20160101.log
#
__xpanes::log_filenames () {
    local _arg_fmt="$1"
    local _full_fmt=$(date '+'$_arg_fmt)
    cat | perl -nle 'print $_."-".(($h{$_}++)+1)' | while read host ; do
        echo $_full_fmt | \
        sed "s/\[:ARG:\]/$host/g" | \
        sed "s/\[:PID:\]/$$/g"
    done
}

#
# Ensure existance of given directory
# Usage:
#        __xpanes::ensure_directory <direname>
#
__xpanes::ensure_directory() {
    local _dir="$1"

    # Remove end of slash '/'
    _dir="${_dir%/}"

    # tilda expansion
    _dir="${_dir/#~/$HOME}"

    # Check directory.
    if [ ! -e "${_dir}" ]; then
        # Create directory
        if mkdir "${_dir}"; then
            echo "${_dir} is created." >&2
        else
            echo "Failed to create ${_dir}" >&2
            exit 1
        fi
    fi
    if [ ! -d "${_dir}" ]; then
        echo "${_dir} is not directory." >&2
        exit 1
    fi
    if [ ! -w "${_dir}" ]; then
        echo "${_dir} is not writable." >&2
        exit 1
    fi

    # Return absolute path
    echo "$(cd "$LOG_DIR" && pwd)"
}

# Convert array to string which is can be used as command line argument.
# Usage:
#       __xpanes::arr2args <array object>
# Example:
#       array=(aaa bbb "ccc ddd" eee "f'f")
#       __xpanes::arr2args "${array[@]}"
#       @returns "'aaa' 'bbb' 'ccc ddd' 'eee' 'f\'f'"
# Result:
__xpanes::arr2args() {
    local _arr=($@)
    local _arg=""
    # If there is no argument, usage will be shown.
    if [ $# -lt 1 ]; then
        return 0
    fi
    for i in $( seq 0 $(( $# - 1)) ) ;do
        _arg=${_arr[i]}
        printf "'${_arg//\'/\\\'}' "
    done
}

# Extract first field separated by dot '.'
# ex, $1       =  aaa.bbb.ccc
#     return   =  aaa-12345(PID)
__xpanes::generate_window_name() {
    echo "$1" | tr '.' ' ' | perl -anle 'printf "$F[0]-'$$'"'
}

#
# Split a new window into multiple panes.
# Usage:
#        run_split <window name> <num of pane>
#
__xpanes::split_window() {
    local _window_name="$1" ; shift
    local _hosts_num="$1"
    for i in $(seq 0 $_hosts_num)
    do
        tmux split-window -t ${_window_name} -h -d
        tmux select-layout even-horizontal

        # Restraining that size of pane's width becomes
        # less than the minimum size which is defined by tmux.
        if [ $i -ge 2 ]; then
            tmux select-layout -t ${_window_name} tiled
        fi
    done
}

__xpanes::enable_logging() {
    local _window_name="$1" ; shift
    local _index_offset="$1" ; shift
    local _log_dir="$1" ; shift
    local _log_format="$1" ; shift
    local _hosts=($@)
    local _hosts_num=$(($# - 1))
    # Generate log files from host list.
    local _logfiles=($(
    for i in $(seq 0 $_hosts_num)
    do
        echo "${_hosts[i]}"
    done | __xpanes::log_filenames "$_log_format"
    ))
    for i in $(seq 0 $_hosts_num)
    do
        # Start logging
        tmux pipe-pane -t ${_window_name}.$(($i + ${_index_offset})) "cat >> '${_log_dir}/${_logfiles[i]}'"
    done
}

__xpanes::send_commands() {
    local _window_name="$1" ; shift
    local _index_offset="$1" ; shift
    local _repstr="$1" ; shift
    local _cmd="$1" ; shift
    local _index=0
    for host in "$@"
    do
        tmux send-keys -t $_window_name.$(($_index + ${_index_offset})) "${_cmd//$_repstr/$host}" C-m
        _index=$(($_index + 1))
    done
}

# Serarate window vertically, when the number of panes is 1 or 2.
__xpanes::arrange_pane_location() {
    local _window_name="$1" ; shift
    local _hosts_num="$1"

    if [ $_hosts_num -eq 1 ]; then
        tmux select-layout -t ${_window_name} even-horizontal
    elif [ $_hosts_num -gt 1 ]; then
        tmux select-layout -t ${_window_name} tiled
    fi
}

#
# Split a new window which was created by tmux into multiple panes.
# Usage:
#        __xpanes::prepare_window <window name> <offset of index> <number of pane>
#
__xpanes::prepare_window()
{
    local _window_name="$1" ; shift
    local _pane_base_index="$1"; shift
    local _pane_num="$1"; shift
    local _no_attach_flg="$1"

    # Create new window.
    if [ $_no_attach_flg -eq 1 ]; then
        # Keep background
        tmux new-window -n "$_window_name" -d
    else
        tmux new-window -n "$_window_name"
    fi

    # specify a pane which has the youngest number of index.
    tmux select-pane -t ${_window_name}.${_pane_base_index}

    # split window into multiple panes
    __xpanes::split_window "$_window_name" "$_pane_num"

    ### If the first pane is still remaining,
    ### panes cannot be organized well.
    # Delete the first pane
    tmux kill-pane -t ${_window_name}.${_pane_base_index}

    # Select second pane
    tmux select-pane -t ${_window_name}.${_pane_base_index}
}

# Following global variables will be used
# within __xpanes::execution function and entrypoint.
: "Initialize options" && {
    HOSTS=()
    OPTIONS=()
    KILL_WIN_FLG=0
    KILL_WIN_NAME=""
    DRY_RUN_FLG=0
    NO_ATTACH_FLG=0
    LOG_STORE_FLG=0
    LOG_DIR="$HOME/.$THIS_FILE_NAME-logs"
    LOG_FORMAT="[:ARG:].log.%Y-%m-%d_%H-%M-%S"
    REPSTR="{}"
    SOCKET_PATH="$HOME/.$THIS_FILE_NAME-socket"
    CMD_UTILITY="echo {} "
}

__xpanes::execution() {

    #
    # If current shell is already in tmux session.
    #
    if [ -n "$TMUX" ]; then
        local _pane_base_index=$(__xpanes::get_tmux_conf 'pane-base-index')
        local _window_name=$(__xpanes::generate_window_name "${HOSTS[0]}")
        local _last_host_idx=$((${#HOSTS[@]} - 1))

        __xpanes::prepare_window "$_window_name" "$_pane_base_index" "$_last_host_idx" "$NO_ATTACH_FLG"

        if [ $LOG_STORE_FLG -eq 1 ]; then
            __xpanes::enable_logging  "$_window_name" "$_pane_base_index" "$LOG_DIR" "$LOG_FORMAT" "${HOSTS[@]}"
        fi

        # Sending ssh opearations for each pane.
        __xpanes::send_commands "$_window_name" "$_pane_base_index" "$REPSTR" "$CMD_UTILITY" "${HOSTS[@]}"

        # This is just the author's preference (You can remove next statement.)
        __xpanes::arrange_pane_location "$_window_name" $_last_host_idx

        # Enable broadcasting
        tmux set-window-option -t ${_window_name} synchronize-panes on

        # Remove original window.
        if [ $KILL_WIN_FLG -eq 1 ]; then
            tmux kill-window -t "$KILL_WIN_NAME"
        fi


    #
    # If current shell is NOT in tmux session.
    #
    else
        # Create new session.
        tmux -S $SOCKET_PATH new-session -s $SESSION_NAME -n $TMP_WIN_NAME -d

        local _hosts4args=$(__xpanes::arr2args "${HOSTS[@]}")
        local _opts4args=$(__xpanes::arr2args "${OPTIONS[@]}")

        tmux -S $SOCKET_PATH send-keys -t $SESSION_NAME:$TMP_WIN_NAME \
            "$ABS_THIS_FILE_NAME --kill-window=$TMP_WIN_NAME $_opts4args $_hosts4args" C-m

        # Avoid attaching if it is unit testing.
        if [ $NO_ATTACH_FLG -eq 0 ]; then
            # Go to another condition of this if statement.
            tmux -S $SOCKET_PATH attach-session -t $SESSION_NAME
        fi
    fi
}

__xpanes::get_opts() {
    # If there is no argument, usage will be shown.
    if [ $# -lt 1 ]; then
        __xpanes::usage
        exit 1
    fi

    while (( $# > 0 ))
    do
        case "$1" in

            # Long options
            --help)
                __xpanes::usage
                exit 0
                ;;
            --version)
                __xpanes::version
                exit 0
                ;;
            --log-format=*)
                OPTIONS=("${OPTIONS[@]}" "$1")
                LOG_STORE_FLG=1
                LOG_FORMAT="${1#--log-format=}"
                shift
                ;;
            --log*)
                OPTIONS=("${OPTIONS[@]}" "$1")
                LOG_STORE_FLG=1
                if [[ "$1" =~ ^--log=  ]]; then
                    LOG_DIR="${1#--log=}"
                fi
                shift
                ;;
            --dry-run)
                DRY_RUN_FLG=1
                shift
                ;;
            --kill-window=*)
                KILL_WIN_FLG="1"
                KILL_WIN_NAME="${1#--kill-window=}"
                shift
                ;;
                # For unit testing
            --no-attach)
                NO_ATTACH_FLG=1
                OPTIONS=("${OPTIONS[@]}" "$1")
                shift
                ;;


            # Short options
            -[hVIcSl]*)
                if [[ "$1" =~ ^-h ]]; then
                    __xpanes::usage
                    exit 0
                fi
                if [[ "$1" =~ ^-V ]]; then
                    __xpanes::version
                    exit 0
                fi

                # Behavior like this.
                # -IAAA         -- REPSTR="AAA"
                # -I AAA BBB    -- REPSTR="AAA"
                # -I"AAA BBB"   -- REPSTR="AAA BBB"
                # -IAAA BBB     -- REPSTR="AAA", HOSTS=("BBB")
                if [[ "$1" =~ ^-I ]]; then
                    OPTIONS=("${OPTIONS[@]}" "$1")
                    if [[ "$1" =~ ^-I.+ ]]; then
                        REPSTR="${1#-I}"
                    elif ! [[ "$2" =~ ^-.* ]]; then
                        REPSTR="$2"
                        shift
                        OPTIONS=("${OPTIONS[@]}" "$1")
                    fi
                fi

                if [[ "$1" =~ ^-c ]]; then
                    OPTIONS=("${OPTIONS[@]}" "$1")
                    if [[ "$1" =~ ^-c.+ ]]; then
                        CMD_UTILITY="${1#-c}"
                    elif ! [[ "$2" =~ ^-.* ]]; then
                        CMD_UTILITY="$2"
                        shift
                        OPTIONS=("${OPTIONS[@]}" "$1")
                    fi
                fi

                if [[ "$1" =~ ^-S ]]; then
                    OPTIONS=("${OPTIONS[@]}" "$1")
                    if [[ "$1" =~ ^-S.+ ]]; then
                        SOCKET_PATH="${1#-I}"
                    elif ! [[ "$2" =~ ^-.* ]]; then
                        SOCKET_PATH="$2"
                        shift
                        OPTIONS=("${OPTIONS[@]}" "$1")
                    fi
                fi

                if [[ "$1" =~ ^-l ]]; then
                    OPTIONS=("${OPTIONS[@]}" "$1")
                    LOG_STORE_FLG=1
                fi
                shift
                ;;

            # Hosts
            *)
                HOSTS=("${HOSTS[@]}" "$1")
                shift
                ;;
        esac
    done
}

__xpanes::is_env_ok () {
    while read cmd ; do
        type $cmd > /dev/null 2>&1
        if [ $? -ne 0 ]; then
            echo "$cmd is required to work." >&2
            exit 1
        fi
    done < <(echo "$XPANES_DEPENDENCIES" | tr ' ' '\n')
    return 0
}


: "Main" && {
    set +e
    __xpanes::is_env_ok
    set -e
    __xpanes::get_opts "$@"

    # When do dry-run flag is enabled, skip running (this is used to execute unit test of itself).
    if [ $DRY_RUN_FLG -ne 1 ]; then

        : "Parameter validation" && {
            if [ ${#HOSTS[@]} -le 0 ]; then
                echo 'Specify hosts.'  >&2
                exit 1
            fi
            # Validate log directory.
            if [ $LOG_STORE_FLG -eq 1 ]; then
                LOG_DIR="$(__xpanes::ensure_directory "$LOG_DIR")"
            fi
        }

        # Run script
        __xpanes::execution
        exit 0
    fi
}
